# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import gestion
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menu(object):

    def __init__(self):
        self.is_ecrir = False
        self.is_research = False
        self.is_import = False

    def out_in_bouton(self, is_out:bool):
       assert type(is_out) == bool
       if is_out:
          self.bouton_0.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 18pt \"Segoe MDL2 Assets\";")
          self.bouton_1.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 18pt \"Segoe MDL2 Assets\";")
          self.bouton_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 18pt \"Segoe MDL2 Assets\";")
          self.bouton_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 18pt \"Segoe MDL2 Assets\";")
          self.bouton_4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 18pt \"Segoe MDL2 Assets\";")
       else:
            self.bouton_0.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Segoe MDL2 Assets\";")
            self.bouton_1.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Segoe MDL2 Assets\";")
            self.bouton_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Segoe MDL2 Assets\";")
            self.bouton_3.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Segoe MDL2 Assets\";")
            self.bouton_4.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Segoe MDL2 Assets\";")

    def bouton0(self):
        exit()

    def bouton1(self):
        self.is_ecrir = True
        self.out_in_bouton(True)
        self.label_nom.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Sitka Text\";")
        self.label_prenom.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Sitka Text\";")
        self.label_telephone.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Sitka Text\";")
        self.lineEdit_nom.setStyleSheet(("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Palatino Linotype\";"))
        self.lineEdit_prenom.setStyleSheet(("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Palatino Linotype\";"))
        self.lineEdit_telephone.setStyleSheet(("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Palatino Linotype\";"))
        self.bouton_confirmer.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 95, 143);\n"
"font: 14pt \"Segoe Script\";")

    def bouton2(self):
        self.is_research = True
        self.out_in_bouton(True)
        self.label_nom.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Sitka Text\";")
        self.label_prenom.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Sitka Text\";")
        self.lineEdit_nom.setStyleSheet(("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Palatino Linotype\";"))
        self.lineEdit_prenom.setStyleSheet(("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Palatino Linotype\";"))
        self.bouton_confirmer.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 95, 143);\n"
"font: 14pt \"Segoe Script\";")

    def bouton3(self):
        contacts = gestion.lecture(True)
        for contact in contacts:
            self.affichage.append(f"{contact[1]}, {contact[2]}, {contact[3]}")

    def bouton4(self):
        self.is_import = True
        self.out_in_bouton(True)
        self.label_fichier.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Sitka Text\";")
        self.lineEdit_fichier.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Palatino Linotype\";")
        self.bouton_confirmer.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 95, 143);\n"
"font: 14pt \"Segoe Script\";")

    def confirmer(self):
        if self.is_ecrir:
           self.is_ecrir = False
           nom = self.lineEdit_nom.text()
           prenom = self.lineEdit_prenom.text()
           telephone = self.lineEdit_telephone.text()
           if gestion.ecriture(nom, prenom, telephone):
              self.affichage.append('Successfull')
           else:
              self.affichage.append('Le numero saisie contient des/une erreur')

           self.label_nom.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Sitka Text\";")
           self.label_prenom.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Sitka Text\";")
           self.label_telephone.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Sitka Text\";")
           self.lineEdit_nom.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Palatino Linotype\";")
           self.lineEdit_prenom.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Palatino Linotype\";")
           self.lineEdit_telephone.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Palatino Linotype\";")
           self.bouton_confirmer.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 14pt \"Segoe Script\";") 
        elif self.is_research:
           self.is_research = False
           nom = self.lineEdit_nom.text()
           prenom = self.lineEdit_prenom.text()
           contact = gestion.lecture(False, nom, prenom)
           if not contact:
              self.affichage.append(f'Aucun contact {nom} {prenom}')
           else:
              self.affichage.append(f"{contact[1]}, {contact[2]}, {contact[3]}")
           self.label_nom.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Sitka Text\";")
           self.label_prenom.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Sitka Text\";")
           self.lineEdit_nom.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Palatino Linotype\";")
           self.lineEdit_prenom.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Palatino Linotype\";")
           self.bouton_confirmer.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 14pt \"Segoe Script\";")
        elif self.is_import:
            self.is_import = False
            fichier = self.lineEdit_fichier.text()
            if gestion.importation(fichier) == False:
               self.affichage.append('Votre fichier ne contient pas les en-têtes (nom, prenom, telephone)' )
            else:
               self.affichage.append('Successfull')
            self.label_fichier.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Sitka Text\";")
            self.lineEdit_fichier.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Palatino Linotype\";")
            self.bouton_confirmer.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 14pt \"Segoe Script\";")
        self.out_in_bouton(False)
        self.lineEdit_fichier.clear()
        self.lineEdit_nom.clear()
        self.lineEdit_prenom.clear()
        self.lineEdit_telephone.clear()
    def setupUi(self, menu):
        menu.setObjectName("menu")
        menu.resize(800, 550)
        menu.setMinimumSize(QtCore.QSize(800, 550))
        menu.setMaximumSize(QtCore.QSize(800, 550))
        menu.setStyleSheet("background-color: rgb(4, 3, 3);")
        self.centralwidget = QtWidgets.QWidget(menu)
        self.centralwidget.setObjectName("centralwidget")
        self.bouton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_0.clicked.connect(self.bouton0)
        self.bouton_0.setGeometry(QtCore.QRect(60, 50, 111, 41))
        self.bouton_0.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Segoe MDL2 Assets\";")
        self.bouton_0.setObjectName("bouton_0")
        self.bouton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_1.clicked.connect(self.bouton1)
        self.bouton_1.setGeometry(QtCore.QRect(60, 130, 111, 41))
        self.bouton_1.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Segoe MDL2 Assets\";")
        self.bouton_1.setObjectName("bouton_1")
        self.bouton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_2.clicked.connect(self.bouton2)
        self.bouton_2.setGeometry(QtCore.QRect(60, 200, 111, 41))
        self.bouton_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Segoe MDL2 Assets\";")
        self.bouton_2.setObjectName("bouton_2")
        self.bouton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_3.clicked.connect(self.bouton3)
        self.bouton_3.setGeometry(QtCore.QRect(60, 270, 111, 41))
        self.bouton_3.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Segoe MDL2 Assets\";")
        self.bouton_3.setObjectName("bouton_3")
        self.bouton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_4.clicked.connect(self.bouton4)
        self.bouton_4.setGeometry(QtCore.QRect(60, 350, 111, 41))
        self.bouton_4.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 18pt \"Segoe MDL2 Assets\";")
        self.bouton_4.setObjectName("bouton_4")
        self.label_nom = QtWidgets.QLabel(self.centralwidget)
        self.label_nom.setGeometry(QtCore.QRect(350, 10, 61, 31))
        self.label_nom.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Sitka Text\";")
        self.label_nom.setObjectName("label_nom")
        self.label_prenom = QtWidgets.QLabel(self.centralwidget)
        self.label_prenom.setGeometry(QtCore.QRect(350, 60, 91, 31))
        self.label_prenom.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Sitka Text\";")
        self.label_prenom.setObjectName("label_prenom")
        self.label_telephone = QtWidgets.QLabel(self.centralwidget)
        self.label_telephone.setGeometry(QtCore.QRect(350, 120, 111, 31))
        self.label_telephone.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Sitka Text\";")
        self.label_telephone.setObjectName("label_telephone")
        self.label_fichier = QtWidgets.QLabel(self.centralwidget)
        self.label_fichier.setGeometry(QtCore.QRect(350, 190, 81, 31))
        self.label_fichier.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 14pt \"Sitka Text\";")
        self.label_fichier.setObjectName("label_fichier")
        self.lineEdit_nom = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nom.setGeometry(QtCore.QRect(440, 9, 151, 31))
        self.lineEdit_nom.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Palatino Linotype\";")
        self.lineEdit_nom.setText("")
        self.lineEdit_nom.setObjectName("lineEdit_nom")
        self.lineEdit_prenom = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_prenom.setGeometry(QtCore.QRect(450, 60, 151, 31))
        self.lineEdit_prenom.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Palatino Linotype\";")
        self.lineEdit_prenom.setText("")
        self.lineEdit_prenom.setObjectName("lineEdit_prenom")
        self.lineEdit_fichier = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_fichier.setGeometry(QtCore.QRect(440, 190, 151, 31))
        self.lineEdit_fichier.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Palatino Linotype\";")
        self.lineEdit_fichier.setText("")
        self.lineEdit_fichier.setObjectName("lineEdit_fichier")
        self.lineEdit_telephone = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_telephone.setGeometry(QtCore.QRect(470, 120, 151, 31))
        self.lineEdit_telephone.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"font: 14pt \"Palatino Linotype\";")
        self.lineEdit_telephone.setText("")
        self.lineEdit_telephone.setObjectName("lineEdit_telephone")
        self.bouton_confirmer = QtWidgets.QPushButton(self.centralwidget)
        self.bouton_confirmer.clicked.connect(self.confirmer)
        self.bouton_confirmer.setGeometry(QtCore.QRect(400, 270, 161, 41))
        self.bouton_confirmer.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 14pt \"Segoe Script\";")
        self.bouton_confirmer.setObjectName("bouton_confirmer")
        self.affichage = QtWidgets.QTextEdit(self.centralwidget)
        self.affichage.setGeometry(QtCore.QRect(320, 330, 451, 171))
        self.affichage.setStyleSheet("font: 16pt \"Segoe UI Emoji\";\n"
"color: rgb(0, 85, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.affichage.setObjectName("affichage")
        menu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(menu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        menu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(menu)
        self.statusbar.setObjectName("statusbar")
        menu.setStatusBar(self.statusbar)

        self.retranslateUi(menu)
        QtCore.QMetaObject.connectSlotsByName(menu)

    def retranslateUi(self, menu):
        _translate = QtCore.QCoreApplication.translate
        menu.setWindowTitle(_translate("menu", "Menu"))
        self.bouton_0.setText(_translate("menu", "0"))
        self.bouton_1.setText(_translate("menu", "1"))
        self.bouton_2.setText(_translate("menu", "2"))
        self.bouton_3.setText(_translate("menu", "3"))
        self.bouton_4.setText(_translate("menu", "4"))
        self.label_nom.setText(_translate("menu", "Nom :"))
        self.label_prenom.setText(_translate("menu", "Prenom :"))
        self.label_telephone.setText(_translate("menu", "téléphone :"))
        self.label_fichier.setText(_translate("menu", "Fichier :"))
        self.bouton_confirmer.setText(_translate("menu", "Confirmer "))
        self.affichage.setHtml(_translate("menu", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI Emoji\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    menu = QtWidgets.QMainWindow()
    ui = Ui_menu()
    ui.setupUi(menu)
    menu.show()
    sys.exit(app.exec_())
